In [1]:
try:
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Note: not using Google CoLab


In [2]:
import tensorflow as tf
print("Tensor Flow Version: {}".format(tf.__version__))

Tensor Flow Version: 2.1.0


In [12]:
matrix1 = tf.constant([[3., 3.]])

# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],
                       [2.]])

# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.matmul(matrix1, matrix2)

print(product)
print(float(product))

tf.Tensor([[12.]], shape=(1, 1), dtype=float32)
12.0


In [8]:
matrix3 = tf.add(matrix1, matrix2)
print(matrix3)
print(matrix1)

tf.Tensor(
[[5. 5.]
 [5. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)


In [29]:
x = tf.Variable([1.0, 2.0])
a = tf.constant([3.0, 3.0])

sub = tf.subtract(x, a)
print("Subtraction : ", sub)
print("Result in Numpy Array : ", sub.numpy())
print("Type of Sub is : {} and {} Type of sub.numpy is : {}".
      format(type(sub), "\n", type(sub.numpy())))


Subtraction :  tf.Tensor([-2. -1.], shape=(2,), dtype=float32)
Result in Numpy Array :  [-2. -1.]
Type of Sub is : <class 'tensorflow.python.framework.ops.EagerTensor'> and 
 Type of sub.numpy is : <class 'numpy.ndarray'>


In [30]:
y = x
print(y)
x.assign([4.0, 6.0])
print(x)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([4., 6.], dtype=float32)>


# Regression

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])

cars = df['name']

# Handle missing value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Pandas to Numpy
x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
y = df['mpg'].values # regression

# Build the neural network
model = Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(10, activation='relu')) # Hidden 2
model.add(Dense(1)) # Output
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Train on 398 samples
Epoch 1/100
398/398 - 1s - loss: 52683.6515
Epoch 2/100
398/398 - 0s - loss: 3793.5328
Epoch 3/100
398/398 - 0s - loss: 2442.9920
Epoch 4/100
398/398 - 0s - loss: 1165.3641
Epoch 5/100
398/398 - 0s - loss: 661.4885
Epoch 6/100
398/398 - 0s - loss: 475.7299
Epoch 7/100
398/398 - 0s - loss: 370.9809
Epoch 8/100
398/398 - 0s - loss: 320.7081
Epoch 9/100
398/398 - 0s - loss: 281.2922
Epoch 10/100
398/398 - 0s - loss: 222.8766
Epoch 11/100
398/398 - 0s - loss: 181.3272
Epoch 12/100
398/398 - 0s - loss: 167.0176
Epoch 13/100
398/398 - 0s - loss: 166.2704
Epoch 14/100
398/398 - 0s - loss: 167.5344
Epoch 15/100
398/398 - 0s - loss: 165.4754
Epoch 16/100
398/398 - 0s - loss: 161.1437
Epoch 17/100
398/398 - 0s - loss: 165.4451
Epoch 18/100
398/398 - 0s - loss: 168.3240
Epoch 19/100
398/398 - 0s - loss: 168.5888
Epoch 20/100
398/398 - 0s - loss: 164.1849
Epoch 21/100
398/398 - 0s - loss: 158.4295
Epoch 22/100
398/398 - 0s - loss: 161.0746
Epoch 23/100
398/398 - 0s - loss: 163

In [37]:
pred = model.predict(x)
print("Shape: {}".format(pred.shape))
#print(pred)

# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Final score (RMSE): {score}")

Shape: (398, 1)
Final score (RMSE): 9.722791569388903


In [38]:
# Sample predictions
for i in range(10):
    print(f"{i+1}. Car name: {cars[i]}, MPG: {y[i]}, predicted MPG: {pred[i]}")

1. Car name: chevrolet chevelle malibu, MPG: 18.0, predicted MPG: [10.384595]
2. Car name: buick skylark 320, MPG: 15.0, predicted MPG: [5.92796]
3. Car name: plymouth satellite, MPG: 18.0, predicted MPG: [6.854443]
4. Car name: amc rebel sst, MPG: 16.0, predicted MPG: [9.544995]
5. Car name: ford torino, MPG: 17.0, predicted MPG: [10.245801]
6. Car name: ford galaxie 500, MPG: 15.0, predicted MPG: [3.9082608]
7. Car name: chevrolet impala, MPG: 14.0, predicted MPG: [-0.6892427]
8. Car name: plymouth fury iii, MPG: 14.0, predicted MPG: [1.1794707]
9. Car name: pontiac catalina, MPG: 14.0, predicted MPG: [0.59875166]
10. Car name: amc ambassador dpl, MPG: 15.0, predicted MPG: [1.3718077]


# Classification

In [39]:
import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

# Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) # Classification
species = dummies.columns
y = dummies.values

# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(25, activation='relu')) # Hidden 2
model.add(Dense(y.shape[1],activation='softmax')) # Output

model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Train on 150 samples
Epoch 1/100
150/150 - 1s - loss: 1.2760
Epoch 2/100
150/150 - 0s - loss: 1.0646
Epoch 3/100
150/150 - 0s - loss: 0.9616
Epoch 4/100
150/150 - 0s - loss: 0.9285
Epoch 5/100
150/150 - 0s - loss: 0.8886
Epoch 6/100
150/150 - 0s - loss: 0.8451
Epoch 7/100
150/150 - 0s - loss: 0.8109
Epoch 8/100
150/150 - 0s - loss: 0.7782
Epoch 9/100
150/150 - 0s - loss: 0.7425
Epoch 10/100
150/150 - 0s - loss: 0.7112
Epoch 11/100
150/150 - 0s - loss: 0.6821
Epoch 12/100
150/150 - 0s - loss: 0.6494
Epoch 13/100
150/150 - 0s - loss: 0.6224
Epoch 14/100
150/150 - 0s - loss: 0.5842
Epoch 15/100
150/150 - 0s - loss: 0.5476
Epoch 16/100
150/150 - 0s - loss: 0.5291
Epoch 17/100
150/150 - 0s - loss: 0.5106
Epoch 18/100
150/150 - 0s - loss: 0.4876
Epoch 19/100
150/150 - 0s - loss: 0.4700
Epoch 20/100
150/150 - 0s - loss: 0.4548
Epoch 21/100
150/150 - 0s - loss: 0.4385
Epoch 22/100
150/150 - 0s - loss: 0.4235
Epoch 23/100
150/150 - 0s - loss: 0.4107
Epoch 24/100
150/150 - 0s - loss: 0.3978
Epoc

In [44]:
print(df['species'])
dummies = pd.get_dummies(df['species']) # Classification
print(dummies)
species = dummies.columns
print(species)
y = dummies.values
print(y)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object
     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]
Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')
[[1 0 0]
 [1 0 0

In [45]:
pred = model.predict(x)
print("Shape: {pred.shape}")
print(pred)

Shape: {pred.shape}
[[9.98692095e-01 1.30742404e-03 4.53485455e-07]
 [9.96113062e-01 3.88440583e-03 2.46389641e-06]
 [9.97772276e-01 2.22629891e-03 1.38409541e-06]
 [9.94566560e-01 5.42888045e-03 4.51339383e-06]
 [9.98824656e-01 1.17491628e-03 4.13840354e-07]
 [9.98241305e-01 1.75833004e-03 4.01703261e-07]
 [9.97337520e-01 2.66080070e-03 1.66683162e-06]
 [9.97704208e-01 2.29483657e-03 1.01014166e-06]
 [9.93336320e-01 6.65619830e-03 7.50198888e-06]
 [9.96285677e-01 3.71201313e-03 2.25824579e-06]
 [9.99008775e-01 9.90936998e-04 2.29800023e-07]
 [9.96374071e-01 3.62394680e-03 2.05380070e-06]
 [9.96512473e-01 3.48521746e-03 2.40921395e-06]
 [9.97956872e-01 2.04118388e-03 1.94806375e-06]
 [9.99819219e-01 1.80784526e-04 1.87499296e-08]
 [9.99687672e-01 3.12309858e-04 3.11822070e-08]
 [9.99486089e-01 5.13732084e-04 9.33712201e-08]
 [9.98464584e-01 1.53484102e-03 5.42200667e-07]
 [9.98532057e-01 1.46770419e-03 2.65504895e-07]
 [9.98789012e-01 1.21064740e-03 3.53076416e-07]
 [9.96637940e-01 3.3

In [46]:
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y,axis=1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {expected_classes}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [47]:
print(species[predict_classes[1:10]])

Index(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'],
      dtype='object')


In [48]:
from sklearn.metrics import accuracy_score
correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.9866666666666667


In [49]:
# ad hoc prediction
sample_flower = np.array( [[5.0,3.0,4.0,2.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict that {sample_flower} is: {species[pred]}")

[[0.00548343 0.56638    0.42813656]]
Predict that [[5. 3. 4. 2.]] is: Iris-versicolor


In [50]:
# predict two sample flowers
sample_flower = np.array( [[5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred,axis=1)
print(f"Predict that these two flowers {sample_flower} are: {species[pred]}")

[[5.4834341e-03 5.6638002e-01 4.2813656e-01]
 [9.9530715e-01 4.6911249e-03 1.7126314e-06]]
Predict that these two flowers [[5.  3.  4.  2. ]
 [5.2 3.5 1.5 0.8]] are: Index(['Iris-versicolor', 'Iris-setosa'], dtype='object')
